# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/vivado_nvdla_prj/Z920_PCIe_AXI_DDR4.xdc

# Block Designs: bd/z920_nvdla_ps/z920_nvdla_ps.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps || ORIG_REF_NAME==z920_nvdla_ps} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_axi_bram_ctrl_1_0/z920_nvdla_ps_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_axi_bram_ctrl_1_0 || ORIG_REF_NAME==z920_nvdla_ps_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_axi_cdma_1_0/z920_nvdla_ps_axi_cdma_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_axi_cdma_1_0 || ORIG_REF_NAME==z920_nvdla_ps_axi_cdma_1_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_axi_interconnect_1_0/z920_nvdla_ps_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_axi_interconnect_1_0 || ORIG_REF_NAME==z920_nvdla_ps_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_axi_interconnect_2_0/z920_nvdla_ps_axi_interconnect_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_axi_interconnect_2_0 || ORIG_REF_NAME==z920_nvdla_ps_axi_interconnect_2_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_axi_interconnect_3_0/z920_nvdla_ps_axi_interconnect_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_axi_interconnect_3_0 || ORIG_REF_NAME==z920_nvdla_ps_axi_interconnect_3_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_blk_mem_gen_1_0/z920_nvdla_ps_blk_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_blk_mem_gen_1_0 || ORIG_REF_NAME==z920_nvdla_ps_blk_mem_gen_1_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/z920_nvdla_ps_ddr4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_ddr4_0_0 || ORIG_REF_NAME==z920_nvdla_ps_ddr4_0_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/ip_0/z920_nvdla_ps_ddr4_0_0_microblaze_mcs.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==z920_nvdla_ps_ddr4_0_0_microblaze_mcs} -quiet] -quiet

# Block Designs: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/bd_0/bd_02cf.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_02cf || ORIG_REF_NAME==bd_02cf} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/bd_0/ip/ip_0/bd_02cf_microblaze_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_02cf_microblaze_I_0 || ORIG_REF_NAME==bd_02cf_microblaze_I_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/bd_0/ip/ip_1/bd_02cf_rst_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_02cf_rst_0_0 || ORIG_REF_NAME==bd_02cf_rst_0_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/bd_0/ip/ip_2/bd_02cf_ilmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_02cf_ilmb_0 || ORIG_REF_NAME==bd_02cf_ilmb_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/bd_0/ip/ip_3/bd_02cf_dlmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_02cf_dlmb_0 || ORIG_REF_NAME==bd_02cf_dlmb_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/bd_0/ip/ip_4/bd_02cf_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_02cf_dlmb_cntlr_0 || ORIG_REF_NAME==bd_02cf_dlmb_cntlr_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/bd_0/ip/ip_5/bd_02cf_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_02cf_ilmb_cntlr_0 || ORIG_REF_NAME==bd_02cf_ilmb_cntlr_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/bd_0/ip/ip_6/bd_02cf_lmb_bram_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_02cf_lmb_bram_I_0 || ORIG_REF_NAME==bd_02cf_lmb_bram_I_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/bd_0/ip/ip_7/bd_02cf_second_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_02cf_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_02cf_second_dlmb_cntlr_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/bd_0/ip/ip_8/bd_02cf_second_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_02cf_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_02cf_second_ilmb_cntlr_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/bd_0/ip/ip_9/bd_02cf_second_lmb_bram_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_02cf_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_02cf_second_lmb_bram_I_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/bd_0/ip/ip_10/bd_02cf_iomodule_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_02cf_iomodule_0_0 || ORIG_REF_NAME==bd_02cf_iomodule_0_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/ip_1/z920_nvdla_ps_ddr4_0_0_phy.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_ddr4_0_0_phy || ORIG_REF_NAME==z920_nvdla_ps_ddr4_0_0_phy} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_proc_sys_reset_0_0/z920_nvdla_ps_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_proc_sys_reset_0_0 || ORIG_REF_NAME==z920_nvdla_ps_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_util_vector_logic_0_0/z920_nvdla_ps_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_util_vector_logic_0_0 || ORIG_REF_NAME==z920_nvdla_ps_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_zynq_ultra_ps_e_0_0/z920_nvdla_ps_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==z920_nvdla_ps_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_xbar_1/z920_nvdla_ps_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_xbar_1 || ORIG_REF_NAME==z920_nvdla_ps_xbar_1} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_xbar_0/z920_nvdla_ps_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_xbar_0 || ORIG_REF_NAME==z920_nvdla_ps_xbar_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_NV_nvdla_wrapper_1_0/z920_nvdla_ps_NV_nvdla_wrapper_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_NV_nvdla_wrapper_1_0 || ORIG_REF_NAME==z920_nvdla_ps_NV_nvdla_wrapper_1_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_axi_apb_bridge_0_0/z920_nvdla_ps_axi_apb_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_axi_apb_bridge_0_0 || ORIG_REF_NAME==z920_nvdla_ps_axi_apb_bridge_0_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_axi_interconnect_0_0/z920_nvdla_ps_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_axi_interconnect_0_0 || ORIG_REF_NAME==z920_nvdla_ps_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_axi_interconnect_4_0/z920_nvdla_ps_axi_interconnect_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_axi_interconnect_4_0 || ORIG_REF_NAME==z920_nvdla_ps_axi_interconnect_4_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_clk_wiz_0_0/z920_nvdla_ps_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_clk_wiz_0_0 || ORIG_REF_NAME==z920_nvdla_ps_clk_wiz_0_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_proc_sys_reset_1_0/z920_nvdla_ps_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_proc_sys_reset_1_0 || ORIG_REF_NAME==z920_nvdla_ps_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_auto_us_1/z920_nvdla_ps_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_auto_us_1 || ORIG_REF_NAME==z920_nvdla_ps_auto_us_1} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_auto_us_0/z920_nvdla_ps_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_auto_us_0 || ORIG_REF_NAME==z920_nvdla_ps_auto_us_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_s00_mmu_0/z920_nvdla_ps_s00_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_s00_mmu_0 || ORIG_REF_NAME==z920_nvdla_ps_s00_mmu_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_auto_ds_2/z920_nvdla_ps_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_auto_ds_2 || ORIG_REF_NAME==z920_nvdla_ps_auto_ds_2} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_auto_ds_1/z920_nvdla_ps_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_auto_ds_1 || ORIG_REF_NAME==z920_nvdla_ps_auto_ds_1} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_auto_pc_2/z920_nvdla_ps_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_auto_pc_2 || ORIG_REF_NAME==z920_nvdla_ps_auto_pc_2} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_auto_ds_0/z920_nvdla_ps_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_auto_ds_0 || ORIG_REF_NAME==z920_nvdla_ps_auto_ds_0} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_auto_pc_1/z920_nvdla_ps_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_auto_pc_1 || ORIG_REF_NAME==z920_nvdla_ps_auto_pc_1} -quiet] -quiet

# IP: bd/z920_nvdla_ps/ip/z920_nvdla_ps_auto_pc_0/z920_nvdla_ps_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_auto_pc_0 || ORIG_REF_NAME==z920_nvdla_ps_auto_pc_0} -quiet] -quiet

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_axi_cdma_1_0/z920_nvdla_ps_axi_cdma_1_0_ooc.xdc

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_axi_cdma_1_0/z920_nvdla_ps_axi_cdma_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_axi_cdma_1_0 || ORIG_REF_NAME==z920_nvdla_ps_axi_cdma_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_blk_mem_gen_1_0/z920_nvdla_ps_blk_mem_gen_1_0_ooc.xdc

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/bd_0/ip/ip_0/bd_02cf_microblaze_I_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_02cf_microblaze_I_0 || ORIG_REF_NAME==bd_02cf_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/bd_0/ip/ip_0/bd_02cf_microblaze_I_0_ooc_debug.xdc

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/bd_0/ip/ip_1/bd_02cf_rst_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_02cf_rst_0_0 || ORIG_REF_NAME==bd_02cf_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/bd_0/ip/ip_1/bd_02cf_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_02cf_rst_0_0 || ORIG_REF_NAME==bd_02cf_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/bd_0/ip/ip_2/bd_02cf_ilmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_02cf_ilmb_0 || ORIG_REF_NAME==bd_02cf_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/bd_0/ip/ip_3/bd_02cf_dlmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_02cf_dlmb_0 || ORIG_REF_NAME==bd_02cf_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/bd_0/ip/ip_6/bd_02cf_lmb_bram_I_0_ooc.xdc

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/bd_0/ip/ip_9/bd_02cf_second_lmb_bram_I_0_ooc.xdc

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/bd_0/ip/ip_10/bd_02cf_iomodule_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_02cf_iomodule_0_0 || ORIG_REF_NAME==bd_02cf_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/bd_0/bd_02cf_ooc.xdc

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/ip_0/z920_nvdla_ps_ddr4_0_0_microblaze_mcs_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_ddr4_0_0_microblaze_mcs || ORIG_REF_NAME==z920_nvdla_ps_ddr4_0_0_microblaze_mcs} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/ip_0/z920_nvdla_ps_ddr4_0_0_microblaze_mcs_ooc.xdc

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/ip_1/par/z920_nvdla_ps_ddr4_0_0_phy_ooc.xdc

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/z920_nvdla_ps_ddr4_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_ddr4_0_0 || ORIG_REF_NAME==z920_nvdla_ps_ddr4_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/par/z920_nvdla_ps_ddr4_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_ddr4_0_0 || ORIG_REF_NAME==z920_nvdla_ps_ddr4_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_proc_sys_reset_0_0/z920_nvdla_ps_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_proc_sys_reset_0_0 || ORIG_REF_NAME==z920_nvdla_ps_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_proc_sys_reset_0_0/z920_nvdla_ps_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_proc_sys_reset_0_0 || ORIG_REF_NAME==z920_nvdla_ps_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_zynq_ultra_ps_e_0_0/z920_nvdla_ps_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_zynq_ultra_ps_e_0_0/z920_nvdla_ps_zynq_ultra_ps_e_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==z920_nvdla_ps_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_NV_nvdla_wrapper_1_0/constrs_1/imports/vivado_nvdla_prj/Z920_PCIe_AXI_DDR4.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_NV_nvdla_wrapper_1_0 || ORIG_REF_NAME==z920_nvdla_ps_NV_nvdla_wrapper_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_axi_apb_bridge_0_0/z920_nvdla_ps_axi_apb_bridge_0_0_ooc.xdc

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_clk_wiz_0_0/z920_nvdla_ps_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_clk_wiz_0_0 || ORIG_REF_NAME==z920_nvdla_ps_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_clk_wiz_0_0/z920_nvdla_ps_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_clk_wiz_0_0 || ORIG_REF_NAME==z920_nvdla_ps_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_clk_wiz_0_0/z920_nvdla_ps_clk_wiz_0_0_ooc.xdc

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_proc_sys_reset_1_0/z920_nvdla_ps_proc_sys_reset_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_proc_sys_reset_1_0 || ORIG_REF_NAME==z920_nvdla_ps_proc_sys_reset_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_proc_sys_reset_1_0/z920_nvdla_ps_proc_sys_reset_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_proc_sys_reset_1_0 || ORIG_REF_NAME==z920_nvdla_ps_proc_sys_reset_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_auto_us_1/z920_nvdla_ps_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_auto_us_1 || ORIG_REF_NAME==z920_nvdla_ps_auto_us_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_auto_us_1/z920_nvdla_ps_auto_us_1_ooc.xdc

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_auto_us_0/z920_nvdla_ps_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_auto_us_0 || ORIG_REF_NAME==z920_nvdla_ps_auto_us_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_auto_us_0/z920_nvdla_ps_auto_us_0_ooc.xdc

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_auto_ds_2/z920_nvdla_ps_auto_ds_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_auto_ds_2 || ORIG_REF_NAME==z920_nvdla_ps_auto_ds_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_auto_ds_2/z920_nvdla_ps_auto_ds_2_ooc.xdc

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_auto_ds_1/z920_nvdla_ps_auto_ds_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_auto_ds_1 || ORIG_REF_NAME==z920_nvdla_ps_auto_ds_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_auto_ds_1/z920_nvdla_ps_auto_ds_1_ooc.xdc

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_auto_pc_2/z920_nvdla_ps_auto_pc_2_ooc.xdc

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_auto_ds_0/z920_nvdla_ps_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z920_nvdla_ps_auto_ds_0 || ORIG_REF_NAME==z920_nvdla_ps_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_auto_ds_0/z920_nvdla_ps_auto_ds_0_ooc.xdc

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_auto_pc_1/z920_nvdla_ps_auto_pc_1_ooc.xdc

# XDC: bd/z920_nvdla_ps/ip/z920_nvdla_ps_auto_pc_0/z920_nvdla_ps_auto_pc_0_ooc.xdc

# XDC: bd/z920_nvdla_ps/z920_nvdla_ps_ooc.xdc
