set_property SRC_FILE_INFO {cfile:/home/sy/work/nvdla_prj/vivado_nvdla_prj/z920_ps_nvdla_latest/project_1/project_1.srcs/sources_1/bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/par/z920_nvdla_ps_ddr4_0_0.xdc rfile:../../../project_1.srcs/sources_1/bd/z920_nvdla_ps/ip/z920_nvdla_ps_ddr4_0_0/par/z920_nvdla_ps_ddr4_0_0.xdc id:1 order:EARLY scoped_inst:z920_nvdla_ps_i/ddr4_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/sy/work/nvdla_prj/vivado_nvdla_prj/z920_ps_nvdla_latest/project_1/project_1.srcs/sources_1/bd/z920_nvdla_ps/ip/z920_nvdla_ps_NV_nvdla_wrapper_1_0/constrs_1/imports/vivado_nvdla_prj/Z920_PCIe_AXI_DDR4.xdc rfile:../../../project_1.srcs/sources_1/bd/z920_nvdla_ps/ip/z920_nvdla_ps_NV_nvdla_wrapper_1_0/constrs_1/imports/vivado_nvdla_prj/Z920_PCIe_AXI_DDR4.xdc id:2 order:EARLY scoped_inst:z920_nvdla_ps_i/NVDLA_system/NV_nvdla_wrapper_1/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/sy/work/nvdla_prj/vivado_nvdla_prj/z920_ps_nvdla_latest/project_1/project_1.srcs/sources_1/bd/z920_nvdla_ps/ip/z920_nvdla_ps_clk_wiz_0_0/z920_nvdla_ps_clk_wiz_0_0.xdc rfile:../../../project_1.srcs/sources_1/bd/z920_nvdla_ps/ip/z920_nvdla_ps_clk_wiz_0_0/z920_nvdla_ps_clk_wiz_0_0.xdc id:3 order:EARLY scoped_inst:z920_nvdla_ps_i/NVDLA_system/clk_wiz_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/sy/work/nvdla_prj/vivado_nvdla_prj/z920_ps_nvdla_latest/project_1/project_1.srcs/constrs_1/imports/vivado_nvdla_prj/Z920_PCIe_AXI_DDR4.xdc rfile:../../../project_1.srcs/constrs_1/imports/vivado_nvdla_prj/Z920_PCIe_AXI_DDR4.xdc id:4} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -end -hold 7 -from [get_pins */u_ddr_cal_top/calDone*/C]
set_property src_info {type:SCOPED_XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -hold -to [get_pins */*/*/*/*/*.u_xiphy_control/xiphy_control/RIU_ADDR*]
set_property src_info {type:SCOPED_XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -hold -to [get_pins */*/*/*/*/*.u_xiphy_control/xiphy_control/RIU_WR_DATA*]
set_property src_info {type:SCOPED_XDC file:1 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 5.0 -datapath_only -from [get_pins */*/*/u_ddr_cal_addr_decode/io_ready_lvl_reg/C] -to [get_pins */u_io_ready_lvl_sync/SYNC[*].sync_reg_reg[0]/D]
set_property src_info {type:SCOPED_XDC file:1 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 5.0 -datapath_only -from [get_pins */*/*/u_ddr_cal_addr_decode/io_read_data_reg[*]/C] -to [get_pins */u_io_read_data_sync/SYNC[*].sync_reg_reg[0]/D]
set_property src_info {type:SCOPED_XDC file:1 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 3.0 -datapath_only -from [get_pins */*/*/phy_ready_riuclk_reg/C] -to [get_pins */u_phy2clb_phy_ready_sync/SYNC[*].sync_reg_reg[0]/D]
set_property src_info {type:SCOPED_XDC file:1 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 3.0 -datapath_only -from [get_pins */*/*/bisc_complete_riuclk_reg/C] -to [get_pins */u_phy2clb_bisc_complete_sync/SYNC[*].sync_reg_reg[0]/D]
set_property src_info {type:SCOPED_XDC file:1 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 3.0 -datapath_only -from [get_pins */*/io_addr_strobe_lvl_riuclk_reg/C] -to [get_pins */u_io_addr_strobe_lvl_sync/SYNC[*].sync_reg_reg[0]/D]
set_property src_info {type:SCOPED_XDC file:1 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 3.0 -datapath_only -from [get_pins */*/io_write_strobe_riuclk_reg/C] -to [get_pins */u_io_write_strobe_sync/SYNC[*].sync_reg_reg[0]/D]
set_property src_info {type:SCOPED_XDC file:1 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 3.0 -datapath_only -from [get_pins */*/io_address_riuclk_reg[*]/C] -to [get_pins */u_io_addr_sync/SYNC[*].sync_reg_reg[0]/D]
set_property src_info {type:SCOPED_XDC file:1 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 3.0 -datapath_only -from [get_pins */*/io_write_data_riuclk_reg[*]/C] -to [get_pins */u_io_write_data_sync/SYNC[*].sync_reg_reg[0]/D]
set_property src_info {type:SCOPED_XDC file:1 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 10.0 -datapath_only -from [get_pins */en_vtc_in_reg/C] -to [get_pins */u_en_vtc_sync/SYNC[*].sync_reg_reg[0]/D]
set_property src_info {type:SCOPED_XDC file:1 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 10.0 -datapath_only -from [get_pins */*/riu2clb_valid_r1_riuclk_reg[*]/C] -to [get_pins */u_riu2clb_valid_sync/SYNC[*].sync_reg_reg[0]/D]
set_property src_info {type:SCOPED_XDC file:1 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 10.0 -datapath_only -from [get_pins */*/*/phy2clb_fixdly_rdy_low_riuclk_int_reg[*]/C] -to [get_pins */u_phy2clb_fixdly_rdy_low/SYNC[*].sync_reg_reg[0]/D]
set_property src_info {type:SCOPED_XDC file:1 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 10.0 -datapath_only -from [get_pins */*/*/phy2clb_fixdly_rdy_upp_riuclk_int_reg[*]/C] -to [get_pins */u_phy2clb_fixdly_rdy_upp/SYNC[*].sync_reg_reg[0]/D]
set_property src_info {type:SCOPED_XDC file:1 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 10.0 -datapath_only -from [get_pins */*/*/phy2clb_phy_rdy_low_riuclk_int_reg[*]/C] -to [get_pins */u_phy2clb_phy_rdy_low/SYNC[*].sync_reg_reg[0]/D]
set_property src_info {type:SCOPED_XDC file:1 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 10.0 -datapath_only -from [get_pins */*/*/phy2clb_phy_rdy_upp_riuclk_int_reg[*]/C] -to [get_pins */u_phy2clb_phy_rdy_upp/SYNC[*].sync_reg_reg[0]/D]
set_property src_info {type:SCOPED_XDC file:1 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 10.0 -datapath_only -from [get_pins */rst_r1_reg/C] -to [get_pins */u_fab_rst_sync/SYNC[*].sync_reg_reg[0]/D]
set_property src_info {type:SCOPED_XDC file:1 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 3.0 -datapath_only -from [get_pins  */*/*/clb2phy_t_b_addr_riuclk_reg/C] -to [get_pins  */*/*/clb2phy_t_b_addr_i_reg[0]/D]
set_property src_info {type:SCOPED_XDC file:1 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 3.0 -datapath_only -from [get_pins  */*/*/*/slave_en_lvl_reg/C] -to [get_pins  */*/*/*/u_slave_en_sync/SYNC[*].sync_reg_reg[0]/D]
set_property src_info {type:SCOPED_XDC file:1 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 3.0 -datapath_only -from [get_pins  */*/*/*/slave_we_r_reg/C] -to [get_pins  */*/*/*/u_slave_we_sync/SYNC[*].sync_reg_reg[0]/D]
set_property src_info {type:SCOPED_XDC file:1 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 3.0 -datapath_only -from [get_pins  */*/*/*/slave_addr_r_reg[*]/C] -to [get_pins  */*/*/*/u_slave_addr_sync/SYNC[*].sync_reg_reg[0]/D]
set_property src_info {type:SCOPED_XDC file:1 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 3.0 -datapath_only -from [get_pins  */*/*/*/slave_di_r_reg[*]/C] -to [get_pins  */*/*/*/u_slave_di_sync/SYNC[*].sync_reg_reg[0]/D]
set_property src_info {type:SCOPED_XDC file:1 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 3.0 -datapath_only -from [get_pins  */*/*/*/slave_rdy_cptd_sclk_reg/C] -to [get_pins  */*/*/*/u_slave_rdy_cptd_sync/SYNC[*].sync_reg_reg[0]/D]
set_property src_info {type:SCOPED_XDC file:1 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 12.0 -datapath_only -from [get_pins */*/*/*/slave_rdy_lvl_fclk_reg/C] -to [get_pins  */*/*/*/u_slave_rdy_sync/SYNC[*].sync_reg_reg[0]/D]
set_property src_info {type:SCOPED_XDC file:1 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay 12.0 -datapath_only -from [get_pins */*/*/*/slave_do_fclk_reg[*]/C] -to [get_pins  */*/*/*/u_slave_do_sync/SYNC[*].sync_reg_reg[0]/D]
set_property src_info {type:SCOPED_XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_ports sys_rst_0]
set_property src_info {type:SCOPED_XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D8 [get_ports sys_rst_0]
set_property src_info {type:SCOPED_XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_0]
set_property src_info {type:SCOPED_XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_HSTL_I_12 [get_ports C0_SYS_CLK_0_clk_p]
set_property src_info {type:SCOPED_XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR27 [get_ports C0_SYS_CLK_0_clk_p]
set_property src_info {type:SCOPED_XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT27 [get_ports C0_SYS_CLK_0_clk_n]
set_property src_info {type:SCOPED_XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_HSTL_I_12 [get_ports C0_SYS_CLK_0_clk_n]
set_property src_info {type:SCOPED_XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN28 [get_ports C0_DDR4_0_act_n]
set_property src_info {type:SCOPED_XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY24 [get_ports {C0_DDR4_0_ba[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV24 [get_ports {C0_DDR4_0_ba[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN24 [get_ports {C0_DDR4_0_bg[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM26 [get_ports {C0_DDR4_0_bg[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU25 [get_ports {C0_DDR4_0_ck_t[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU26 [get_ports {C0_DDR4_0_ck_c[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM28 [get_ports {C0_DDR4_0_cke[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT25 [get_ports {C0_DDR4_0_cs_n[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN23 [get_ports {C0_DDR4_0_odt[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN26 [get_ports C0_DDR4_0_reset_n]
set_property src_info {type:SCOPED_XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW27 [get_ports {C0_DDR4_0_adr[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW26 [get_ports {C0_DDR4_0_adr[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR25 [get_ports {C0_DDR4_0_adr[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV26 [get_ports {C0_DDR4_0_adr[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR24 [get_ports {C0_DDR4_0_adr[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT28 [get_ports {C0_DDR4_0_adr[5]}]
set_property src_info {type:SCOPED_XDC file:2 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW25 [get_ports {C0_DDR4_0_adr[6]}]
set_property src_info {type:SCOPED_XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP24 [get_ports {C0_DDR4_0_adr[7]}]
set_property src_info {type:SCOPED_XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR28 [get_ports {C0_DDR4_0_adr[8]}]
set_property src_info {type:SCOPED_XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP25 [get_ports {C0_DDR4_0_adr[9]}]
set_property src_info {type:SCOPED_XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT26 [get_ports {C0_DDR4_0_adr[10]}]
set_property src_info {type:SCOPED_XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP27 [get_ports {C0_DDR4_0_adr[11]}]
set_property src_info {type:SCOPED_XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM24 [get_ports {C0_DDR4_0_adr[12]}]
set_property src_info {type:SCOPED_XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL23 [get_ports {C0_DDR4_0_adr[13]}]
set_property src_info {type:SCOPED_XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR23 [get_ports {C0_DDR4_0_adr[14]}]
set_property src_info {type:SCOPED_XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU24 [get_ports {C0_DDR4_0_adr[15]}]
set_property src_info {type:SCOPED_XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT23 [get_ports {C0_DDR4_0_adr[16]}]
set_property src_info {type:SCOPED_XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM19 [get_ports {C0_DDR4_0_dm_n[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT22 [get_ports {C0_DDR4_0_dm_n[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU23 [get_ports {C0_DDR4_0_dm_n[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA23 [get_ports {C0_DDR4_0_dm_n[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV17 [get_ports {C0_DDR4_0_dm_n[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY17 [get_ports {C0_DDR4_0_dm_n[5]}]
set_property src_info {type:SCOPED_XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY12 [get_ports {C0_DDR4_0_dm_n[6]}]
set_property src_info {type:SCOPED_XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ18 [get_ports {C0_DDR4_0_dm_n[7]}]
set_property src_info {type:SCOPED_XDC file:2 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK22 [get_ports {C0_DDR4_0_dq[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ20 [get_ports {C0_DDR4_0_dq[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM21 [get_ports {C0_DDR4_0_dq[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM20 [get_ports {C0_DDR4_0_dq[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ22 [get_ports {C0_DDR4_0_dq[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ21 [get_ports {C0_DDR4_0_dq[5]}]
set_property src_info {type:SCOPED_XDC file:2 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL21 [get_ports {C0_DDR4_0_dq[6]}]
set_property src_info {type:SCOPED_XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL22 [get_ports {C0_DDR4_0_dq[7]}]
set_property src_info {type:SCOPED_XDC file:2 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP22 [get_ports {C0_DDR4_0_dq[8]}]
set_property src_info {type:SCOPED_XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP20 [get_ports {C0_DDR4_0_dq[9]}]
set_property src_info {type:SCOPED_XDC file:2 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT20 [get_ports {C0_DDR4_0_dq[10]}]
set_property src_info {type:SCOPED_XDC file:2 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR19 [get_ports {C0_DDR4_0_dq[11]}]
set_property src_info {type:SCOPED_XDC file:2 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN22 [get_ports {C0_DDR4_0_dq[12]}]
set_property src_info {type:SCOPED_XDC file:2 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP19 [get_ports {C0_DDR4_0_dq[13]}]
set_property src_info {type:SCOPED_XDC file:2 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR20 [get_ports {C0_DDR4_0_dq[14]}]
set_property src_info {type:SCOPED_XDC file:2 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU19 [get_ports {C0_DDR4_0_dq[15]}]
set_property src_info {type:SCOPED_XDC file:2 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV19 [get_ports {C0_DDR4_0_dq[16]}]
set_property src_info {type:SCOPED_XDC file:2 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV21 [get_ports {C0_DDR4_0_dq[17]}]
set_property src_info {type:SCOPED_XDC file:2 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW22 [get_ports {C0_DDR4_0_dq[18]}]
set_property src_info {type:SCOPED_XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW19 [get_ports {C0_DDR4_0_dq[19]}]
set_property src_info {type:SCOPED_XDC file:2 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU20 [get_ports {C0_DDR4_0_dq[20]}]
set_property src_info {type:SCOPED_XDC file:2 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU21 [get_ports {C0_DDR4_0_dq[21]}]
set_property src_info {type:SCOPED_XDC file:2 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV22 [get_ports {C0_DDR4_0_dq[22]}]
set_property src_info {type:SCOPED_XDC file:2 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW20 [get_ports {C0_DDR4_0_dq[23]}]
set_property src_info {type:SCOPED_XDC file:2 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY22 [get_ports {C0_DDR4_0_dq[24]}]
set_property src_info {type:SCOPED_XDC file:2 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB19 [get_ports {C0_DDR4_0_dq[25]}]
set_property src_info {type:SCOPED_XDC file:2 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA18 [get_ports {C0_DDR4_0_dq[26]}]
set_property src_info {type:SCOPED_XDC file:2 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB20 [get_ports {C0_DDR4_0_dq[27]}]
set_property src_info {type:SCOPED_XDC file:2 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY23 [get_ports {C0_DDR4_0_dq[28]}]
set_property src_info {type:SCOPED_XDC file:2 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA22 [get_ports {C0_DDR4_0_dq[29]}]
set_property src_info {type:SCOPED_XDC file:2 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB18 [get_ports {C0_DDR4_0_dq[30]}]
set_property src_info {type:SCOPED_XDC file:2 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA21 [get_ports {C0_DDR4_0_dq[31]}]
set_property src_info {type:SCOPED_XDC file:2 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT17 [get_ports {C0_DDR4_0_dq[32]}]
set_property src_info {type:SCOPED_XDC file:2 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU18 [get_ports {C0_DDR4_0_dq[33]}]
set_property src_info {type:SCOPED_XDC file:2 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR17 [get_ports {C0_DDR4_0_dq[34]}]
set_property src_info {type:SCOPED_XDC file:2 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU15 [get_ports {C0_DDR4_0_dq[35]}]
set_property src_info {type:SCOPED_XDC file:2 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU16 [get_ports {C0_DDR4_0_dq[36]}]
set_property src_info {type:SCOPED_XDC file:2 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV18 [get_ports {C0_DDR4_0_dq[37]}]
set_property src_info {type:SCOPED_XDC file:2 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT15 [get_ports {C0_DDR4_0_dq[38]}]
set_property src_info {type:SCOPED_XDC file:2 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT16 [get_ports {C0_DDR4_0_dq[39]}]
set_property src_info {type:SCOPED_XDC file:2 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA16 [get_ports {C0_DDR4_0_dq[40]}]
set_property src_info {type:SCOPED_XDC file:2 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW16 [get_ports {C0_DDR4_0_dq[41]}]
set_property src_info {type:SCOPED_XDC file:2 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY14 [get_ports {C0_DDR4_0_dq[42]}]
set_property src_info {type:SCOPED_XDC file:2 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB13 [get_ports {C0_DDR4_0_dq[43]}]
set_property src_info {type:SCOPED_XDC file:2 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW17 [get_ports {C0_DDR4_0_dq[44]}]
set_property src_info {type:SCOPED_XDC file:2 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB16 [get_ports {C0_DDR4_0_dq[45]}]
set_property src_info {type:SCOPED_XDC file:2 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY15 [get_ports {C0_DDR4_0_dq[46]}]
set_property src_info {type:SCOPED_XDC file:2 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA13 [get_ports {C0_DDR4_0_dq[47]}]
set_property src_info {type:SCOPED_XDC file:2 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB11 [get_ports {C0_DDR4_0_dq[48]}]
set_property src_info {type:SCOPED_XDC file:2 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW15 [get_ports {C0_DDR4_0_dq[49]}]
set_property src_info {type:SCOPED_XDC file:2 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA11 [get_ports {C0_DDR4_0_dq[50]}]
set_property src_info {type:SCOPED_XDC file:2 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU14 [get_ports {C0_DDR4_0_dq[51]}]
set_property src_info {type:SCOPED_XDC file:2 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW14 [get_ports {C0_DDR4_0_dq[52]}]
set_property src_info {type:SCOPED_XDC file:2 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV14 [get_ports {C0_DDR4_0_dq[53]}]
set_property src_info {type:SCOPED_XDC file:2 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB10 [get_ports {C0_DDR4_0_dq[54]}]
set_property src_info {type:SCOPED_XDC file:2 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA10 [get_ports {C0_DDR4_0_dq[55]}]
set_property src_info {type:SCOPED_XDC file:2 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN16 [get_ports {C0_DDR4_0_dq[56]}]
set_property src_info {type:SCOPED_XDC file:2 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN17 [get_ports {C0_DDR4_0_dq[57]}]
set_property src_info {type:SCOPED_XDC file:2 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM18 [get_ports {C0_DDR4_0_dq[58]}]
set_property src_info {type:SCOPED_XDC file:2 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL18 [get_ports {C0_DDR4_0_dq[59]}]
set_property src_info {type:SCOPED_XDC file:2 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN18 [get_ports {C0_DDR4_0_dq[60]}]
set_property src_info {type:SCOPED_XDC file:2 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP16 [get_ports {C0_DDR4_0_dq[61]}]
set_property src_info {type:SCOPED_XDC file:2 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM16 [get_ports {C0_DDR4_0_dq[62]}]
set_property src_info {type:SCOPED_XDC file:2 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL16 [get_ports {C0_DDR4_0_dq[63]}]
set_property src_info {type:SCOPED_XDC file:2 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK20 [get_ports {C0_DDR4_0_dqs_t[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK19 [get_ports {C0_DDR4_0_dqs_c[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN21 [get_ports {C0_DDR4_0_dqs_t[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP21 [get_ports {C0_DDR4_0_dqs_c[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY19 [get_ports {C0_DDR4_0_dqs_t[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY18 [get_ports {C0_DDR4_0_dqs_c[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY20 [get_ports {C0_DDR4_0_dqs_t[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA20 [get_ports {C0_DDR4_0_dqs_c[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR18 [get_ports {C0_DDR4_0_dqs_t[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT18 [get_ports {C0_DDR4_0_dqs_c[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA15 [get_ports {C0_DDR4_0_dqs_t[5]}]
set_property src_info {type:SCOPED_XDC file:2 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB15 [get_ports {C0_DDR4_0_dqs_c[5]}]
set_property src_info {type:SCOPED_XDC file:2 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU13 [get_ports {C0_DDR4_0_dqs_t[6]}]
set_property src_info {type:SCOPED_XDC file:2 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV13 [get_ports {C0_DDR4_0_dqs_c[6]}]
set_property src_info {type:SCOPED_XDC file:2 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ17 [get_ports {C0_DDR4_0_dqs_t[7]}]
set_property src_info {type:SCOPED_XDC file:2 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK17 [get_ports {C0_DDR4_0_dqs_c[7]}]
set_property src_info {type:SCOPED_XDC file:2 line:196 export:INPUT save:INPUT read:READ} [current_design]
create_pblock z920_nvdla_ps_i_NVDLA_system_NV_nvdla_wrapper_1_inst_pblock_ddr4_0
resize_pblock [get_pblocks z920_nvdla_ps_i_NVDLA_system_NV_nvdla_wrapper_1_inst_pblock_ddr4_0] -add {SLICE_X22Y0:SLICE_X104Y659}
resize_pblock [get_pblocks z920_nvdla_ps_i_NVDLA_system_NV_nvdla_wrapper_1_inst_pblock_ddr4_0] -add {RAMB18_X2Y0:RAMB18_X7Y263}
resize_pblock [get_pblocks z920_nvdla_ps_i_NVDLA_system_NV_nvdla_wrapper_1_inst_pblock_ddr4_0] -add {RAMB36_X2Y0:RAMB36_X7Y131}
set_property src_info {type:SCOPED_XDC file:2 line:197 export:INPUT save:INPUT read:READ} [current_design]
add_cells_to_pblock [get_pblocks pblock_ddr4_0] [get_cells -quiet [list Z920_PCIe_AXI_DDR4_i/ddr4_0]]
set_property src_info {type:SCOPED_XDC file:2 line:201 export:INPUT save:INPUT read:READ} [current_design]
resize_pblock [get_pblocks pblock_ddr4_0] -add {DSP48E2_X2Y0DSP48E2_X7Y263}
set_property src_info {type:SCOPED_XDC file:3 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.064
set_property src_info {type:XDC file:4 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D8 [get_ports sys_rst_0]
set_property src_info {type:XDC file:4 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR27 [get_ports C0_SYS_CLK_0_clk_p]
set_property src_info {type:XDC file:4 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT27 [get_ports C0_SYS_CLK_0_clk_n]
set_property src_info {type:XDC file:4 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN28 [get_ports C0_DDR4_0_act_n]
set_property src_info {type:XDC file:4 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY24 [get_ports {C0_DDR4_0_ba[0]}]
set_property src_info {type:XDC file:4 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV24 [get_ports {C0_DDR4_0_ba[1]}]
set_property src_info {type:XDC file:4 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN24 [get_ports {C0_DDR4_0_bg[0]}]
set_property src_info {type:XDC file:4 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM26 [get_ports {C0_DDR4_0_bg[1]}]
set_property src_info {type:XDC file:4 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU25 [get_ports {C0_DDR4_0_ck_t[0]}]
set_property src_info {type:XDC file:4 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU26 [get_ports {C0_DDR4_0_ck_c[0]}]
set_property src_info {type:XDC file:4 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM28 [get_ports {C0_DDR4_0_cke[0]}]
set_property src_info {type:XDC file:4 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT25 [get_ports {C0_DDR4_0_cs_n[0]}]
set_property src_info {type:XDC file:4 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN23 [get_ports {C0_DDR4_0_odt[0]}]
set_property src_info {type:XDC file:4 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN26 [get_ports C0_DDR4_0_reset_n]
set_property src_info {type:XDC file:4 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW27 [get_ports {C0_DDR4_0_adr[0]}]
set_property src_info {type:XDC file:4 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW26 [get_ports {C0_DDR4_0_adr[1]}]
set_property src_info {type:XDC file:4 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR25 [get_ports {C0_DDR4_0_adr[2]}]
set_property src_info {type:XDC file:4 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV26 [get_ports {C0_DDR4_0_adr[3]}]
set_property src_info {type:XDC file:4 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR24 [get_ports {C0_DDR4_0_adr[4]}]
set_property src_info {type:XDC file:4 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT28 [get_ports {C0_DDR4_0_adr[5]}]
set_property src_info {type:XDC file:4 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW25 [get_ports {C0_DDR4_0_adr[6]}]
set_property src_info {type:XDC file:4 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP24 [get_ports {C0_DDR4_0_adr[7]}]
set_property src_info {type:XDC file:4 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR28 [get_ports {C0_DDR4_0_adr[8]}]
set_property src_info {type:XDC file:4 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP25 [get_ports {C0_DDR4_0_adr[9]}]
set_property src_info {type:XDC file:4 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT26 [get_ports {C0_DDR4_0_adr[10]}]
set_property src_info {type:XDC file:4 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP27 [get_ports {C0_DDR4_0_adr[11]}]
set_property src_info {type:XDC file:4 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM24 [get_ports {C0_DDR4_0_adr[12]}]
set_property src_info {type:XDC file:4 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL23 [get_ports {C0_DDR4_0_adr[13]}]
set_property src_info {type:XDC file:4 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR23 [get_ports {C0_DDR4_0_adr[14]}]
set_property src_info {type:XDC file:4 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU24 [get_ports {C0_DDR4_0_adr[15]}]
set_property src_info {type:XDC file:4 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT23 [get_ports {C0_DDR4_0_adr[16]}]
set_property src_info {type:XDC file:4 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM19 [get_ports {C0_DDR4_0_dm_n[0]}]
set_property src_info {type:XDC file:4 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT22 [get_ports {C0_DDR4_0_dm_n[1]}]
set_property src_info {type:XDC file:4 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU23 [get_ports {C0_DDR4_0_dm_n[2]}]
set_property src_info {type:XDC file:4 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA23 [get_ports {C0_DDR4_0_dm_n[3]}]
set_property src_info {type:XDC file:4 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV17 [get_ports {C0_DDR4_0_dm_n[4]}]
set_property src_info {type:XDC file:4 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY17 [get_ports {C0_DDR4_0_dm_n[5]}]
set_property src_info {type:XDC file:4 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY12 [get_ports {C0_DDR4_0_dm_n[6]}]
set_property src_info {type:XDC file:4 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ18 [get_ports {C0_DDR4_0_dm_n[7]}]
set_property src_info {type:XDC file:4 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK22 [get_ports {C0_DDR4_0_dq[0]}]
set_property src_info {type:XDC file:4 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ20 [get_ports {C0_DDR4_0_dq[1]}]
set_property src_info {type:XDC file:4 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM21 [get_ports {C0_DDR4_0_dq[2]}]
set_property src_info {type:XDC file:4 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM20 [get_ports {C0_DDR4_0_dq[3]}]
set_property src_info {type:XDC file:4 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ22 [get_ports {C0_DDR4_0_dq[4]}]
set_property src_info {type:XDC file:4 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ21 [get_ports {C0_DDR4_0_dq[5]}]
set_property src_info {type:XDC file:4 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL21 [get_ports {C0_DDR4_0_dq[6]}]
set_property src_info {type:XDC file:4 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL22 [get_ports {C0_DDR4_0_dq[7]}]
set_property src_info {type:XDC file:4 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP22 [get_ports {C0_DDR4_0_dq[8]}]
set_property src_info {type:XDC file:4 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP20 [get_ports {C0_DDR4_0_dq[9]}]
set_property src_info {type:XDC file:4 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT20 [get_ports {C0_DDR4_0_dq[10]}]
set_property src_info {type:XDC file:4 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR19 [get_ports {C0_DDR4_0_dq[11]}]
set_property src_info {type:XDC file:4 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN22 [get_ports {C0_DDR4_0_dq[12]}]
set_property src_info {type:XDC file:4 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP19 [get_ports {C0_DDR4_0_dq[13]}]
set_property src_info {type:XDC file:4 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR20 [get_ports {C0_DDR4_0_dq[14]}]
set_property src_info {type:XDC file:4 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU19 [get_ports {C0_DDR4_0_dq[15]}]
set_property src_info {type:XDC file:4 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV19 [get_ports {C0_DDR4_0_dq[16]}]
set_property src_info {type:XDC file:4 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV21 [get_ports {C0_DDR4_0_dq[17]}]
set_property src_info {type:XDC file:4 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW22 [get_ports {C0_DDR4_0_dq[18]}]
set_property src_info {type:XDC file:4 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW19 [get_ports {C0_DDR4_0_dq[19]}]
set_property src_info {type:XDC file:4 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU20 [get_ports {C0_DDR4_0_dq[20]}]
set_property src_info {type:XDC file:4 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU21 [get_ports {C0_DDR4_0_dq[21]}]
set_property src_info {type:XDC file:4 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV22 [get_ports {C0_DDR4_0_dq[22]}]
set_property src_info {type:XDC file:4 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW20 [get_ports {C0_DDR4_0_dq[23]}]
set_property src_info {type:XDC file:4 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY22 [get_ports {C0_DDR4_0_dq[24]}]
set_property src_info {type:XDC file:4 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB19 [get_ports {C0_DDR4_0_dq[25]}]
set_property src_info {type:XDC file:4 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA18 [get_ports {C0_DDR4_0_dq[26]}]
set_property src_info {type:XDC file:4 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB20 [get_ports {C0_DDR4_0_dq[27]}]
set_property src_info {type:XDC file:4 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY23 [get_ports {C0_DDR4_0_dq[28]}]
set_property src_info {type:XDC file:4 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA22 [get_ports {C0_DDR4_0_dq[29]}]
set_property src_info {type:XDC file:4 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB18 [get_ports {C0_DDR4_0_dq[30]}]
set_property src_info {type:XDC file:4 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA21 [get_ports {C0_DDR4_0_dq[31]}]
set_property src_info {type:XDC file:4 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT17 [get_ports {C0_DDR4_0_dq[32]}]
set_property src_info {type:XDC file:4 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU18 [get_ports {C0_DDR4_0_dq[33]}]
set_property src_info {type:XDC file:4 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR17 [get_ports {C0_DDR4_0_dq[34]}]
set_property src_info {type:XDC file:4 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU15 [get_ports {C0_DDR4_0_dq[35]}]
set_property src_info {type:XDC file:4 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU16 [get_ports {C0_DDR4_0_dq[36]}]
set_property src_info {type:XDC file:4 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV18 [get_ports {C0_DDR4_0_dq[37]}]
set_property src_info {type:XDC file:4 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT15 [get_ports {C0_DDR4_0_dq[38]}]
set_property src_info {type:XDC file:4 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT16 [get_ports {C0_DDR4_0_dq[39]}]
set_property src_info {type:XDC file:4 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA16 [get_ports {C0_DDR4_0_dq[40]}]
set_property src_info {type:XDC file:4 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW16 [get_ports {C0_DDR4_0_dq[41]}]
set_property src_info {type:XDC file:4 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY14 [get_ports {C0_DDR4_0_dq[42]}]
set_property src_info {type:XDC file:4 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB13 [get_ports {C0_DDR4_0_dq[43]}]
set_property src_info {type:XDC file:4 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW17 [get_ports {C0_DDR4_0_dq[44]}]
set_property src_info {type:XDC file:4 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB16 [get_ports {C0_DDR4_0_dq[45]}]
set_property src_info {type:XDC file:4 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY15 [get_ports {C0_DDR4_0_dq[46]}]
set_property src_info {type:XDC file:4 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA13 [get_ports {C0_DDR4_0_dq[47]}]
set_property src_info {type:XDC file:4 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB11 [get_ports {C0_DDR4_0_dq[48]}]
set_property src_info {type:XDC file:4 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW15 [get_ports {C0_DDR4_0_dq[49]}]
set_property src_info {type:XDC file:4 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA11 [get_ports {C0_DDR4_0_dq[50]}]
set_property src_info {type:XDC file:4 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU14 [get_ports {C0_DDR4_0_dq[51]}]
set_property src_info {type:XDC file:4 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW14 [get_ports {C0_DDR4_0_dq[52]}]
set_property src_info {type:XDC file:4 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV14 [get_ports {C0_DDR4_0_dq[53]}]
set_property src_info {type:XDC file:4 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB10 [get_ports {C0_DDR4_0_dq[54]}]
set_property src_info {type:XDC file:4 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA10 [get_ports {C0_DDR4_0_dq[55]}]
set_property src_info {type:XDC file:4 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN16 [get_ports {C0_DDR4_0_dq[56]}]
set_property src_info {type:XDC file:4 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN17 [get_ports {C0_DDR4_0_dq[57]}]
set_property src_info {type:XDC file:4 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM18 [get_ports {C0_DDR4_0_dq[58]}]
set_property src_info {type:XDC file:4 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL18 [get_ports {C0_DDR4_0_dq[59]}]
set_property src_info {type:XDC file:4 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN18 [get_ports {C0_DDR4_0_dq[60]}]
set_property src_info {type:XDC file:4 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP16 [get_ports {C0_DDR4_0_dq[61]}]
set_property src_info {type:XDC file:4 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM16 [get_ports {C0_DDR4_0_dq[62]}]
set_property src_info {type:XDC file:4 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL16 [get_ports {C0_DDR4_0_dq[63]}]
set_property src_info {type:XDC file:4 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK20 [get_ports {C0_DDR4_0_dqs_t[0]}]
set_property src_info {type:XDC file:4 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK19 [get_ports {C0_DDR4_0_dqs_c[0]}]
set_property src_info {type:XDC file:4 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN21 [get_ports {C0_DDR4_0_dqs_t[1]}]
set_property src_info {type:XDC file:4 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP21 [get_ports {C0_DDR4_0_dqs_c[1]}]
set_property src_info {type:XDC file:4 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY19 [get_ports {C0_DDR4_0_dqs_t[2]}]
set_property src_info {type:XDC file:4 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY18 [get_ports {C0_DDR4_0_dqs_c[2]}]
set_property src_info {type:XDC file:4 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY20 [get_ports {C0_DDR4_0_dqs_t[3]}]
set_property src_info {type:XDC file:4 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA20 [get_ports {C0_DDR4_0_dqs_c[3]}]
set_property src_info {type:XDC file:4 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR18 [get_ports {C0_DDR4_0_dqs_t[4]}]
set_property src_info {type:XDC file:4 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT18 [get_ports {C0_DDR4_0_dqs_c[4]}]
set_property src_info {type:XDC file:4 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA15 [get_ports {C0_DDR4_0_dqs_t[5]}]
set_property src_info {type:XDC file:4 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB15 [get_ports {C0_DDR4_0_dqs_c[5]}]
set_property src_info {type:XDC file:4 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU13 [get_ports {C0_DDR4_0_dqs_t[6]}]
set_property src_info {type:XDC file:4 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV13 [get_ports {C0_DDR4_0_dqs_c[6]}]
set_property src_info {type:XDC file:4 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ17 [get_ports {C0_DDR4_0_dqs_t[7]}]
set_property src_info {type:XDC file:4 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK17 [get_ports {C0_DDR4_0_dqs_c[7]}]
set_property src_info {type:XDC file:4 line:196 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_ddr4_0
resize_pblock [get_pblocks pblock_ddr4_0] -add {SLICE_X22Y0:SLICE_X104Y659}
resize_pblock [get_pblocks pblock_ddr4_0] -add {RAMB18_X2Y0:RAMB18_X7Y263}
resize_pblock [get_pblocks pblock_ddr4_0] -add {RAMB36_X2Y0:RAMB36_X7Y131}
set_property src_info {type:XDC file:4 line:197 export:INPUT save:INPUT read:READ} [current_design]
add_cells_to_pblock [get_pblocks pblock_ddr4_0] [get_cells -quiet [list Z920_PCIe_AXI_DDR4_i/ddr4_0]]
set_property src_info {type:XDC file:4 line:201 export:INPUT save:INPUT read:READ} [current_design]
resize_pblock [get_pblocks pblock_ddr4_0] -add {DSP48E2_X2Y0DSP48E2_X7Y263}
