###############################################################################
# User Time Names / User Time Groups / Time Specs
###############################################################################
#create_clock -period 10.000 -name sys_clk [get_ports {IBUF_DS_P_0[0]}]
#create_clock -period 10.000 -name {IBUF_DS_P_0[0]} -waveform {0.000 5.000} [get_ports {IBUF_DS_P_0[0]}]
#set_false_path -from [get_ports sys_rst_n_0]
set_false_path -from [get_ports sys_rst_0]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]

###############################################################################
# Pinout and Related I/O Constraints
###############################################################################
#PCIE rst
#set_property PULLUP true [get_ports sys_rst_n_0]
#set_property IOSTANDARD LVCMOS18 [get_ports sys_rst_n_0]
#set_property PACKAGE_PIN D2 [get_ports sys_rst_n_0]

#set_property LOC [get_package_pins -filter {PIN_FUNC == IO_T3U_N12_PERSTN0_65}] [get_ports sys_rst_n_0]

#DDR4 rst
set_property PACKAGE_PIN D8 [get_ports sys_rst_0]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_0]

#set_property PACKAGE_PIN AH11 [get_ports {IBUF_DS_N_0[0]}]
#set_property PACKAGE_PIN AH12 [get_ports {IBUF_DS_P_0[0]}]

#PCIe


#set_property PACKAGE_PIN AE2 [get_ports {pci_exp_rxp_0[0]}]
#set_property PACKAGE_PIN AD8 [get_ports {pci_exp_txp_0[0]}]
#set_property PACKAGE_PIN AF4 [get_ports {pci_exp_rxp_0[1]}]
#set_property PACKAGE_PIN AE6 [get_ports {pci_exp_txp_0[1]}]
#set_property PACKAGE_PIN AG2 [get_ports {pci_exp_rxp_0[2]}]
#set_property PACKAGE_PIN AF8 [get_ports {pci_exp_txp_0[2]}]
#set_property PACKAGE_PIN AH4 [get_ports {pci_exp_rxp_0[3]}]
#set_property PACKAGE_PIN AG6 [get_ports {pci_exp_txp_0[3]}]
#set_property PACKAGE_PIN AJ2 [get_ports {pci_exp_rxp_0[4]}]
#set_property PACKAGE_PIN AH8 [get_ports {pci_exp_txp_0[4]}]
#set_property PACKAGE_PIN AK4 [get_ports {pci_exp_rxp_0[5]}]
#set_property PACKAGE_PIN AJ6 [get_ports {pci_exp_txp_0[5]}]
#set_property PACKAGE_PIN AL2 [get_ports {pci_exp_rxp_0[6]}]
#set_property PACKAGE_PIN AK8 [get_ports {pci_exp_txp_0[6]}]
#set_property PACKAGE_PIN AM4 [get_ports {pci_exp_rxp_0[7]}]
#set_property PACKAGE_PIN AL6 [get_ports {pci_exp_txp_0[7]}]

#DDR4
#set_property PACKAGE_PIN A3 [get_ports c0_init_calib_complete_0]

set_property IOSTANDARD DIFF_HSTL_I_12 [get_ports C0_SYS_CLK_0_clk_p]

set_property PACKAGE_PIN AR27 [get_ports C0_SYS_CLK_0_clk_p]
set_property PACKAGE_PIN AT27 [get_ports C0_SYS_CLK_0_clk_n]
set_property IOSTANDARD DIFF_HSTL_I_12 [get_ports C0_SYS_CLK_0_clk_n]

set_property PACKAGE_PIN AN28 [get_ports C0_DDR4_0_act_n]

set_property PACKAGE_PIN AY24 [get_ports {C0_DDR4_0_ba[0]}]
set_property PACKAGE_PIN AV24 [get_ports {C0_DDR4_0_ba[1]}]
set_property PACKAGE_PIN AN24 [get_ports {C0_DDR4_0_bg[0]}]
set_property PACKAGE_PIN AM26 [get_ports {C0_DDR4_0_bg[1]}]
set_property PACKAGE_PIN AU25 [get_ports {C0_DDR4_0_ck_t[0]}]
set_property PACKAGE_PIN AU26 [get_ports {C0_DDR4_0_ck_c[0]}]
#set_property PACKAGE_PIN AV28 [ get_ports "c0_ddr4_ck_c[1]" ]
#set_property PACKAGE_PIN AU28 [ get_ports "c0_ddr4_ck_t[1]" ]
set_property PACKAGE_PIN AM28 [get_ports {C0_DDR4_0_cke[0]}]
#set_property PACKAGE_PIN AN27 [ get_ports "C0_DDR4_0_cke[1]" ]
set_property PACKAGE_PIN AT25 [get_ports {C0_DDR4_0_cs_n[0]}]
#set_property PACKAGE_PIN AK24 [ get_ports "C0_DDR4_0_cs_n[1]" ]
#set_property PACKAGE_PIN AM23 [ get_ports "C0_DDR4_0_cs_n[2]" ]
#set_property PACKAGE_PIN AJ24 [ get_ports "C0_DDR4_0_cs_n[3]" ]
set_property PACKAGE_PIN AN23 [get_ports {C0_DDR4_0_odt[0]}]
#set_property PACKAGE_PIN AK23 [ get_ports "C0_DDR4_0_odt[1]" ]
set_property PACKAGE_PIN AN26 [get_ports C0_DDR4_0_reset_n]

set_property PACKAGE_PIN AW27 [get_ports {C0_DDR4_0_adr[0]}]
set_property PACKAGE_PIN AW26 [get_ports {C0_DDR4_0_adr[1]}]
set_property PACKAGE_PIN AR25 [get_ports {C0_DDR4_0_adr[2]}]
set_property PACKAGE_PIN AV26 [get_ports {C0_DDR4_0_adr[3]}]
set_property PACKAGE_PIN AR24 [get_ports {C0_DDR4_0_adr[4]}]
set_property PACKAGE_PIN AT28 [get_ports {C0_DDR4_0_adr[5]}]
set_property PACKAGE_PIN AW25 [get_ports {C0_DDR4_0_adr[6]}]
set_property PACKAGE_PIN AP24 [get_ports {C0_DDR4_0_adr[7]}]
set_property PACKAGE_PIN AR28 [get_ports {C0_DDR4_0_adr[8]}]
set_property PACKAGE_PIN AP25 [get_ports {C0_DDR4_0_adr[9]}]
set_property PACKAGE_PIN AT26 [get_ports {C0_DDR4_0_adr[10]}]
set_property PACKAGE_PIN AP27 [get_ports {C0_DDR4_0_adr[11]}]
set_property PACKAGE_PIN AM24 [get_ports {C0_DDR4_0_adr[12]}]
set_property PACKAGE_PIN AL23 [get_ports {C0_DDR4_0_adr[13]}]
set_property PACKAGE_PIN AR23 [get_ports {C0_DDR4_0_adr[14]}]
set_property PACKAGE_PIN AU24 [get_ports {C0_DDR4_0_adr[15]}]
set_property PACKAGE_PIN AT23 [get_ports {C0_DDR4_0_adr[16]}]

set_property PACKAGE_PIN AM19 [get_ports {C0_DDR4_0_dm_n[0]}]
set_property PACKAGE_PIN AT22 [get_ports {C0_DDR4_0_dm_n[1]}]
set_property PACKAGE_PIN AU23 [get_ports {C0_DDR4_0_dm_n[2]}]
set_property PACKAGE_PIN BA23 [get_ports {C0_DDR4_0_dm_n[3]}]
set_property PACKAGE_PIN AV17 [get_ports {C0_DDR4_0_dm_n[4]}]
set_property PACKAGE_PIN AY17 [get_ports {C0_DDR4_0_dm_n[5]}]
set_property PACKAGE_PIN AY12 [get_ports {C0_DDR4_0_dm_n[6]}]
set_property PACKAGE_PIN AJ18 [get_ports {C0_DDR4_0_dm_n[7]}]
#set_property PACKAGE_PIN AW24 [ get_ports "C0_DDR4_0_dm_n[8]" ]

set_property PACKAGE_PIN AK22 [get_ports {C0_DDR4_0_dq[0]}]
set_property PACKAGE_PIN AJ20 [get_ports {C0_DDR4_0_dq[1]}]
set_property PACKAGE_PIN AM21 [get_ports {C0_DDR4_0_dq[2]}]
set_property PACKAGE_PIN AM20 [get_ports {C0_DDR4_0_dq[3]}]
set_property PACKAGE_PIN AJ22 [get_ports {C0_DDR4_0_dq[4]}]
set_property PACKAGE_PIN AJ21 [get_ports {C0_DDR4_0_dq[5]}]
set_property PACKAGE_PIN AL21 [get_ports {C0_DDR4_0_dq[6]}]
set_property PACKAGE_PIN AL22 [get_ports {C0_DDR4_0_dq[7]}]
set_property PACKAGE_PIN AP22 [get_ports {C0_DDR4_0_dq[8]}]
set_property PACKAGE_PIN AP20 [get_ports {C0_DDR4_0_dq[9]}]
set_property PACKAGE_PIN AT20 [get_ports {C0_DDR4_0_dq[10]}]
set_property PACKAGE_PIN AR19 [get_ports {C0_DDR4_0_dq[11]}]
set_property PACKAGE_PIN AN22 [get_ports {C0_DDR4_0_dq[12]}]
set_property PACKAGE_PIN AP19 [get_ports {C0_DDR4_0_dq[13]}]
set_property PACKAGE_PIN AR20 [get_ports {C0_DDR4_0_dq[14]}]
set_property PACKAGE_PIN AU19 [get_ports {C0_DDR4_0_dq[15]}]
set_property PACKAGE_PIN AV19 [get_ports {C0_DDR4_0_dq[16]}]
set_property PACKAGE_PIN AV21 [get_ports {C0_DDR4_0_dq[17]}]
set_property PACKAGE_PIN AW22 [get_ports {C0_DDR4_0_dq[18]}]
set_property PACKAGE_PIN AW19 [get_ports {C0_DDR4_0_dq[19]}]
set_property PACKAGE_PIN AU20 [get_ports {C0_DDR4_0_dq[20]}]
set_property PACKAGE_PIN AU21 [get_ports {C0_DDR4_0_dq[21]}]
set_property PACKAGE_PIN AV22 [get_ports {C0_DDR4_0_dq[22]}]
set_property PACKAGE_PIN AW20 [get_ports {C0_DDR4_0_dq[23]}]
set_property PACKAGE_PIN AY22 [get_ports {C0_DDR4_0_dq[24]}]
set_property PACKAGE_PIN BB19 [get_ports {C0_DDR4_0_dq[25]}]
set_property PACKAGE_PIN BA18 [get_ports {C0_DDR4_0_dq[26]}]
set_property PACKAGE_PIN BB20 [get_ports {C0_DDR4_0_dq[27]}]
set_property PACKAGE_PIN AY23 [get_ports {C0_DDR4_0_dq[28]}]
set_property PACKAGE_PIN BA22 [get_ports {C0_DDR4_0_dq[29]}]
set_property PACKAGE_PIN BB18 [get_ports {C0_DDR4_0_dq[30]}]
set_property PACKAGE_PIN BA21 [get_ports {C0_DDR4_0_dq[31]}]
set_property PACKAGE_PIN AT17 [get_ports {C0_DDR4_0_dq[32]}]
set_property PACKAGE_PIN AU18 [get_ports {C0_DDR4_0_dq[33]}]
set_property PACKAGE_PIN AR17 [get_ports {C0_DDR4_0_dq[34]}]
set_property PACKAGE_PIN AU15 [get_ports {C0_DDR4_0_dq[35]}]
set_property PACKAGE_PIN AU16 [get_ports {C0_DDR4_0_dq[36]}]
set_property PACKAGE_PIN AV18 [get_ports {C0_DDR4_0_dq[37]}]
set_property PACKAGE_PIN AT15 [get_ports {C0_DDR4_0_dq[38]}]
set_property PACKAGE_PIN AT16 [get_ports {C0_DDR4_0_dq[39]}]
set_property PACKAGE_PIN BA16 [get_ports {C0_DDR4_0_dq[40]}]
set_property PACKAGE_PIN AW16 [get_ports {C0_DDR4_0_dq[41]}]
set_property PACKAGE_PIN AY14 [get_ports {C0_DDR4_0_dq[42]}]
set_property PACKAGE_PIN BB13 [get_ports {C0_DDR4_0_dq[43]}]
set_property PACKAGE_PIN AW17 [get_ports {C0_DDR4_0_dq[44]}]
set_property PACKAGE_PIN BB16 [get_ports {C0_DDR4_0_dq[45]}]
set_property PACKAGE_PIN AY15 [get_ports {C0_DDR4_0_dq[46]}]
set_property PACKAGE_PIN BA13 [get_ports {C0_DDR4_0_dq[47]}]
set_property PACKAGE_PIN BB11 [get_ports {C0_DDR4_0_dq[48]}]
set_property PACKAGE_PIN AW15 [get_ports {C0_DDR4_0_dq[49]}]
set_property PACKAGE_PIN BA11 [get_ports {C0_DDR4_0_dq[50]}]
set_property PACKAGE_PIN AU14 [get_ports {C0_DDR4_0_dq[51]}]
set_property PACKAGE_PIN AW14 [get_ports {C0_DDR4_0_dq[52]}]
set_property PACKAGE_PIN AV14 [get_ports {C0_DDR4_0_dq[53]}]
set_property PACKAGE_PIN BB10 [get_ports {C0_DDR4_0_dq[54]}]
set_property PACKAGE_PIN BA10 [get_ports {C0_DDR4_0_dq[55]}]
set_property PACKAGE_PIN AN16 [get_ports {C0_DDR4_0_dq[56]}]
set_property PACKAGE_PIN AN17 [get_ports {C0_DDR4_0_dq[57]}]
set_property PACKAGE_PIN AM18 [get_ports {C0_DDR4_0_dq[58]}]
set_property PACKAGE_PIN AL18 [get_ports {C0_DDR4_0_dq[59]}]
set_property PACKAGE_PIN AN18 [get_ports {C0_DDR4_0_dq[60]}]
set_property PACKAGE_PIN AP16 [get_ports {C0_DDR4_0_dq[61]}]
set_property PACKAGE_PIN AM16 [get_ports {C0_DDR4_0_dq[62]}]
set_property PACKAGE_PIN AL16 [get_ports {C0_DDR4_0_dq[63]}]
#set_property PACKAGE_PIN BA28 [ get_ports "C0_DDR4_0_dq[64]" ]
#set_property PACKAGE_PIN AY27 [ get_ports "C0_DDR4_0_dq[65]" ]
#set_property PACKAGE_PIN BB24 [ get_ports "C0_DDR4_0_dq[66]" ]
#set_property PACKAGE_PIN AY25 [ get_ports "C0_DDR4_0_dq[67]" ]
#set_property PACKAGE_PIN AY28 [ get_ports "C0_DDR4_0_dq[68]" ]
#set_property PACKAGE_PIN BB28 [ get_ports "C0_DDR4_0_dq[69]" ]
#set_property PACKAGE_PIN BB25 [ get_ports "C0_DDR4_0_dq[70]" ]
#set_property PACKAGE_PIN BA25 [ get_ports "C0_DDR4_0_dq[71]" ]

#set_property PACKAGE_PIN BB26 [ get_ports "C0_DDR4_0_dqs_c[8]" ]
set_property PACKAGE_PIN AK20 [get_ports {C0_DDR4_0_dqs_t[0]}]
set_property PACKAGE_PIN AK19 [get_ports {C0_DDR4_0_dqs_c[0]}]
set_property PACKAGE_PIN AN21 [get_ports {C0_DDR4_0_dqs_t[1]}]
set_property PACKAGE_PIN AP21 [get_ports {C0_DDR4_0_dqs_c[1]}]
set_property PACKAGE_PIN AY19 [get_ports {C0_DDR4_0_dqs_t[2]}]
set_property PACKAGE_PIN AY18 [get_ports {C0_DDR4_0_dqs_c[2]}]
set_property PACKAGE_PIN AY20 [get_ports {C0_DDR4_0_dqs_t[3]}]
set_property PACKAGE_PIN BA20 [get_ports {C0_DDR4_0_dqs_c[3]}]
set_property PACKAGE_PIN AR18 [get_ports {C0_DDR4_0_dqs_t[4]}]
set_property PACKAGE_PIN AT18 [get_ports {C0_DDR4_0_dqs_c[4]}]
set_property PACKAGE_PIN BA15 [get_ports {C0_DDR4_0_dqs_t[5]}]
set_property PACKAGE_PIN BB15 [get_ports {C0_DDR4_0_dqs_c[5]}]
set_property PACKAGE_PIN AU13 [get_ports {C0_DDR4_0_dqs_t[6]}]
set_property PACKAGE_PIN AV13 [get_ports {C0_DDR4_0_dqs_c[6]}]
set_property PACKAGE_PIN AJ17 [get_ports {C0_DDR4_0_dqs_t[7]}]
set_property PACKAGE_PIN AK17 [get_ports {C0_DDR4_0_dqs_c[7]}]
#set_property PACKAGE_PIN BA26 [ get_ports "C0_DDR4_0_dqs_t[8]" ]

create_pblock pblock_ddr4_0
add_cells_to_pblock [get_pblocks pblock_ddr4_0] [get_cells -quiet [list Z920_PCIe_AXI_DDR4_i/ddr4_0]]
resize_pblock [get_pblocks pblock_ddr4_0] -add {SLICE_X22Y0:SLICE_X104Y659}
resize_pblock [get_pblocks pblock_ddr4_0] -add {RAMB18_X2Y0:RAMB18_X7Y263}
resize_pblock [get_pblocks pblock_ddr4_0] -add {RAMB36_X2Y0:RAMB36_X7Y131}
resize_pblock [get_pblocks pblock_ddr4_0] -add {DSP48E2_X2Y0DSP48E2_X7Y263}





